### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by show0me0love** [Roller44/ns2-experiences#1]
感谢分享，尤其nsbench已很难找到相关资源

**Comment by Roller44** [comment]
不客气。这个项目是很久以前的了，我对它已经生疏，希望能够对你有帮助。
________________________________
From: ***@***.*** ***@***.***> on behalf of show0me0love ***@***.***>
Sent: Sunday, April 7, 2024 11:06 PM
To: Roller44/ns2-experiences ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Roller44/ns2-experiences] thanks (Issue #1)


感谢分享，尤其nsbench已很难找到相关资源

―
